CREATE TABLE CUSTOMER
(
  CustomerID INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15),
  Email VARCHAR(50) UNIQUE,
);

CREATE TABLE PRODUCT
(
  ProductID INT NOT NULL,
  TypeProduct NVARCHAR(50) NOT NULL,
  ProductName NVARCHAR(100) NOT NULL UNIQUE,
  Size VARCHAR(10),
  Price INT NOT NULL,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ProductID)
);

CREATE TABLE STAFF
(
  StaffID INT NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  DateStartWork SMALLDATETIME NOT NULL,
  RoleStaff NVARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL UNIQUE,
  Salary BIGINT NOT NULL,
  Allowance INT,
  CONSTRAINT PK_STAFF PRIMARY KEY (StaffID)
);

CREATE TABLE SUPPLIER
(
  SupplierID INT NOT NULL,
  SupplierName NVARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  PhoneNumber VARCHAR(15) NOT NULL,
  TradingName NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (SupplierID)
);

CREATE TABLE ITEM
(
  ItemID INT NOT NULL,
  SupplierID INT NOT NULL,
  ItemName NVARCHAR(100) NOT NULL,
  TypeItem NVARCHAR(50) NOT NULL,
  SupplyDate SMALLDATETIME NOT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (ItemID),
  CONSTRAINT FK_ITEM_SUPPLIER FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID)
);

CREATE TABLE USED_IN
(
  ProductID INT NOT NULL,
  ItemID INT NOT NULL,
  ItemWeight NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_USED_IN PRIMARY KEY (ProductID, ItemID),
  CONSTRAINT FK_USED_IN_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  CONSTRAINT FK_USED_IN_ITEM FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID)
);

CREATE TABLE ORDERS
(
  OrderID INT NOT NULL,
  CustomerID INT NOT NULL,
  StaffID INT NOT NULL,
  OrderDate DATETIME NOT NULL,
  StatusOrders NVARCHAR(50) NOT NULL,
  LocationOrders NVARCHAR(255) NOT NULL,
  TotalPrice BIGINT NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (OrderID),
  CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
  CONSTRAINT FK_ORDERS_STAFF FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE ORDERDETAIL
(  
  ProductID INT NOT NULL,
  OrderID INT NOT NULL,
  Price INT NOT NULL,
  Quantity INT NOT NULL,
  TotalPrice AS (Price * Quantity),
  CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ProductID, OrderID),
  CONSTRAINT FK_ORDERDETAIL_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  CONSTRAINT FK_ORDERDETAIL_ORDERS FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);
