CREATE TABLE CUSTOMER
(
  CustomerID INT NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15),
  Email VARCHAR(50) UNIQUE,
  CONSTRAINT PK_CUSTOMER PRIMARY KEY (CustomerID)
);

CREATE TABLE PRODUCT
(
  ProductID INT NOT NULL,
  Price INT NOT NULL,
  TypeProduct NVARCHAR(50) NOT NULL,
  Size VARCHAR(10) NOT NULL,
  ProductName NVARCHAR(100) NOT NULL UNIQUE,
  CONSTRAINT PK_PRODUCT PRIMARY KEY (ProductID)
);

CREATE TABLE STAFF
(
  StaffID INT NOT NULL,
  FirstName NVARCHAR(50) NOT NULL,
  LastName NVARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL UNIQUE,
  RoleStaff NVARCHAR(50) NOT NULL,
  Salary BIGINT NOT NULL,
  DateStartWork SMALLDATETIME NOT NULL,
  Allowance INT,
  CONSTRAINT PK_STAFF PRIMARY KEY (StaffID)
);

CREATE TABLE SUPPLIER
(
  SupplierID INT NOT NULL,
  SupplierName NVARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL UNIQUE,
  PhoneNumber VARCHAR(15) NOT NULL,
  TradingName NVARCHAR(50) NOT NULL,
  CONSTRAINT PK_SUPPLIER PRIMARY KEY (SupplierID)
);

CREATE TABLE ITEM
(
  ItemID INT NOT NULL,
  TypeItem NVARCHAR(50) NOT NULL,
  ItemName NVARCHAR(100) NOT NULL,
  SupplyDate SMALLDATETIME NOT NULL,
  SupplierID INT NOT NULL,
  CONSTRAINT PK_ITEM PRIMARY KEY (ItemID),
  CONSTRAINT FK_ITEM_SUPPLIER FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID)
);

CREATE TABLE USED_IN
(
  Quantity INT NOT NULL,
  ProductID INT NOT NULL,
  ItemID INT NOT NULL,
  CONSTRAINT PK_USED_IN PRIMARY KEY (ProductID, ItemID),
  CONSTRAINT FK_USED_IN_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  CONSTRAINT FK_USED_IN_ITEM FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID)
);

CREATE TABLE ORDERS
(
  OrderID INT NOT NULL,
  OrderDate DATETIME NOT NULL,
  TotalPrice BIGINT NOT NULL,
  StatusOrders INT NOT NULL,
  LocationOrders NVARCHAR(255) NOT NULL,
  CustomerID INT NOT NULL,
  StaffID INT NOT NULL,
  CONSTRAINT PK_ORDERS PRIMARY KEY (OrderID),
  CONSTRAINT FK_ORDERS_CUSTOMER FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID),
  CONSTRAINT FK_ORDERS_STAFF FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE ORDERDETAIL
(
  Price INT NOT NULL,
  Quantity INT NOT NULL,
  TotalPrice BIGINT NOT NULL,
  ProductID INT NOT NULL,
  OrderID INT NOT NULL,
  CONSTRAINT PK_ORDERDETAIL PRIMARY KEY (ProductID, OrderID),
  CONSTRAINT FK_ORDERDETAIL_PRODUCT FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  CONSTRAINT FK_ORDERDETAIL_ORDERS FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

alter table ORDERS 
 alter column StatusOrders nvarchar(50) not null;

 alter table USED_IN 
 alter column Quantity nvarchar(50) not null;