CREATE TABLE CUSTOMER
(
  CustomerID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15),
  Email VARCHAR(50)
);

CREATE TABLE PRODUCT
(
  ProductID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  Price BIGINT NOT NULL,
  TypeProduct VARCHAR(50) NOT NULL,
  Size VARCHAR(10) NOT NULL,
  Rate SMALLINT NOT NULL,
  ProductName VARCHAR(100) NOT NULL
);

CREATE TABLE ORDERS
(
  OrderID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  OrdersDate DATE NOT NULL,
  TotalPrice BIGINT NOT NULL,
  OrderStatus VARCHAR(20) NOT NULL,
  Location VARCHAR(50) NOT NULL,
  CustomerID INT NOT NULL,
  FOREIGN KEY (CustomerID) REFERENCES CUSTOMER(CustomerID)
);

CREATE TABLE STAFF
(
  StaffID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  FirstName VARCHAR(50) NOT NULL,
  LastName VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  StaffRole VARCHAR(50) NOT NULL,
  Salary BIGINT NOT NULL,
  DateStartWork DATE NOT NULL,
  Allowance INT
);

CREATE TABLE ITEM
(
  ItemID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  ItemType VARCHAR(50) NOT NULL,
  ItemName VARCHAR(100) NOT NULL,
  Quantity INT NOT NULL
);

CREATE TABLE USED_IN
(
  ProductID INT NOT NULL,
  ItemID INT NOT NULL,
  PRIMARY KEY (ProductID, ItemID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID)
);

CREATE TABLE FULLFILL
(
  OrderID INT NOT NULL,
  StaffID INT NOT NULL,
  PRIMARY KEY (OrderID, StaffID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID),
  FOREIGN KEY (StaffID) REFERENCES STAFF(StaffID)
);

CREATE TABLE ORDERDETAIL
(
  Price INT NOT NULL,
  Quantity SMALLINT NOT NULL,
  TotalPrice BIGINT NOT NULL,
  ProductID INT NOT NULL,
  OrderID INT NOT NULL,
  PRIMARY KEY (ProductID, OrderID),
  FOREIGN KEY (ProductID) REFERENCES PRODUCT(ProductID),
  FOREIGN KEY (OrderID) REFERENCES ORDERS(OrderID)
);

CREATE TABLE SUPPLIER
(
  SupplierID INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
  SupplierName VARCHAR(50) NOT NULL,
  Email VARCHAR(50) NOT NULL,
  PhoneNumber VARCHAR(15) NOT NULL,
  TradingName VARCHAR(50) NOT NULL,
  ItemID INT NOT NULL,
  FOREIGN KEY (ItemID) REFERENCES ITEM(ItemID)
);
